name = "TWA"
uuid = "872ea9bc-b301-4732-bc26-d1af4c7707df"
authors = ["Javad Vahedi"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
