"""
    dtwa_rhs!(du, u, model, t)

Evaluate the closed-system DTWA equations of motion for one trajectory.

The phase-space state `u` and derivative `du` use the package-wide
single-trajectory layout

    (nsites, 3)

with Cartesian columns `(x, y, z)`.

# Hamiltonian convention

The current model layer is interpreted in Pauli variables,

    H = Σ_{i<j,a} Jᵃᵢⱼ σᵃᵢ σᵃⱼ
        + Σ_{i,a} hᵃ σᵃᵢ,

so the classical DTWA coordinates are the Weyl symbols of Pauli
operators and initially take values `±1`.

Using `[σᵃ, σᵇ] = 2im εₐᵦ𝚌 σᶜ`, the deterministic closed-system
equation is

    dsᵢ/dt = 2 h_eff,i × sᵢ,

where

    h_eff,iᵃ = hᵃ + Σ_{j≠i} Jᵃᵢⱼ sⱼᵃ.

The time argument `t` is accepted for compatibility with ODE solvers;
the Hamiltonians currently implemented by the package are autonomous.

This is the direct model-level reference kernel. A later compilation
layer can replace repeated model queries with precomputed sparse
coupling data without changing this public equation-of-motion contract.
"""
function dtwa_rhs!(
    du::AbstractMatrix,
    u::AbstractMatrix,
    model::SpinModel,
    t,
)
    nsites = model.geometry.nsites

    _check_dtwa_dynamics_layout(du, u, nsites)

    fill!(du, zero(eltype(du)))

    hx, hy, hz = _model_field_components(model)

    # Uniform one-body field contribution:
    #
    #     ds/dt = 2 h × s
    #
    @inbounds for i in 1:nsites
        sx = u[i, 1]
        sy = u[i, 2]
        sz = u[i, 3]

        du[i, 1] += 2 * (hy * sz - hz * sy)
        du[i, 2] += 2 * (hz * sx - hx * sz)
        du[i, 3] += 2 * (hx * sy - hy * sx)
    end

    # Pair contribution. Each unordered pair is visited exactly once.
    # Updating both sites in the same loop avoids allocating a separate
    # effective-field array.
    @inbounds for i in 1:(nsites - 1)
        six = u[i, 1]
        siy = u[i, 2]
        siz = u[i, 3]

        for j in (i + 1):nsites
            Jx, Jy, Jz = coupling_components(
                model,
                i,
                j,
            )

            # Skip absent pairs early. This keeps the reference kernel
            # simple while avoiding the arithmetic work for zero bonds.
            iszero(Jx) && iszero(Jy) && iszero(Jz) &&
                continue

            sjx = u[j, 1]
            sjy = u[j, 2]
            sjz = u[j, 3]

            # Effective field on i generated by site j.
            hix = Jx * sjx
            hiy = Jy * sjy
            hiz = Jz * sjz

            du[i, 1] += 2 * (hiy * siz - hiz * siy)
            du[i, 2] += 2 * (hiz * six - hix * siz)
            du[i, 3] += 2 * (hix * siy - hiy * six)

            # Effective field on j generated by site i.
            hjx = Jx * six
            hjy = Jy * siy
            hjz = Jz * siz

            du[j, 1] += 2 * (hjy * sjz - hjz * sjy)
            du[j, 2] += 2 * (hjz * sjx - hjx * sjz)
            du[j, 3] += 2 * (hjx * sjy - hjy * sjx)
        end
    end

    return nothing
end


"""
    _model_field_components(model)

Return the total uniform Cartesian field `(hx, hy, hz)` obtained by
summing all `Field` terms in a model Hamiltonian.

Pair-interaction terms contribute zero.
"""
@inline function _model_field_components(
    model::SpinModel,
)
    return _sum_field_components(model.hamiltonian.terms)
end


@inline _sum_field_components(::Tuple{}) = (0, 0, 0)

@inline function _sum_field_components(
    terms::Tuple,
)
    current = _term_field_components(first(terms))
    rest = _sum_field_components(Base.tail(terms))

    return (
        current[1] + rest[1],
        current[2] + rest[2],
        current[3] + rest[3],
    )
end


@inline _term_field_components(
    field::AbstractField,
) = field_components(field)

@inline _term_field_components(
    ::AbstractCouplingProfile,
) = (0, 0, 0)


"""
    _check_dtwa_dynamics_layout(du, u, nsites)

Validate the matrix layout expected by the single-trajectory DTWA
dynamics kernel.
"""
@inline function _check_dtwa_dynamics_layout(
    du::AbstractMatrix,
    u::AbstractMatrix,
    nsites::Integer,
)
    size(u) == (nsites, 3) ||
        throw(DimensionMismatch(
            "u must have size ($nsites, 3); got $(size(u))",
        ))

    size(du) == size(u) ||
        throw(DimensionMismatch(
            "du must have size $(size(u)); got $(size(du))",
        ))

    return nothing
end
